minor changes

diff --git a/utils/h2o/h2oflowctl b/utils/h2o/h2oflowctl
--- a/utils/h2o/h2oflowctl
+++ b/utils/h2o/h2oflowctl
@@ -2,31 +2,31 @@
 # tested against  a AWS EC2 instance with a Linux 2 VM (Ubuntu)
 
 set -eu
-trap "{ echo 'ERROR - H2O UI failed' ; exit 255; }" SIGINT SIGTERM ERR
+trap "{ echo 'ERROR - H2O Flow UI failed' ; exit 255; }" SIGINT SIGTERM ERR
 
 # TODO check h2o for existence
 # TODO check java for existence
 
-[[ $# -eq 1 ]] || { echo 'ERROR - H2O action failed'; exit 255; }
+[[ $# -eq 1 ]] || { echo 'ERROR - H2O Flow missing action'; exit 255; }
 
 action=$1
 
 case $action in
   start)
     #TODO timestamp sur le log
-    ! tmux has-session -t h2o 2>/dev/null && {
-      echo "=== starting H2O Web UI"
-      tmux new -d -s h2o bash -c "cd /opt/h2o; java -jar h2o.jar" &
+    ! tmux has-session -t h2oflow 2>/dev/null && {
+      echo "=== starting H2O Flow Web UI"
+      tmux new -d -s h2oflow bash -c "cd /opt/h2o; java -jar h2o.jar | tee -a /var/log/aidemos/h2o/h2oflow.out" &
       echo "INFO - H2O started"
     }
     # TODO check for existence
     ;;
   stop)
-    ! tmux has-session -t h2o  2>/dev/null && {
+    ! tmux has-session -t h2oflow  2>/dev/null && {
       #TODO log arret
-      echo "=== stopping H2O"
-      tmux kil-session -t h2o
-      echo "INFO - H2O stopped"
+      echo "=== stopping H2O Flow"
+      tmux kil-session -t h2oflow
+      echo "INFO - H2O Flow stopped"
     }
     ;;
   *)
